services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: sistemaegresso
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Vitoria@20022001
    ports:
      - "5432:5432"
    volumes:
        - ./src/main/resources/db:/docker-entrypoint-initdb.d
        - postgres_data:/var/lib/postgresql/data
volumes:
    postgres_data: