services:

  db:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DATABASE: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./iniciar.sql:/docker-entrypoint-initdb.d/iniciar.sql